# Generated by Django 4.2.2 on 2023-06-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='country',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
