# Generated by Django 4.2.2 on 2023-06-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_appuser_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_active',
        ),
    ]
