# Generated by Django 4.2.2 on 2023-06-18 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
